[2025-04-23T20:13:53.339+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/test.py
[2025-04-23T20:13:53.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:13:53.347+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:13:53.346+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:13:53.377+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:13:53.371+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:13:53.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:13:53.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.077 seconds
[2025-04-23T20:14:24.014+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/test.py
[2025-04-23T20:14:24.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:14:24.017+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:14:24.017+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:14:24.038+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:14:24.033+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:14:24.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:14:24.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.059 seconds
[2025-04-23T20:14:54.813+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/test.py
[2025-04-23T20:14:54.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:14:54.817+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:14:54.817+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:14:54.843+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:14:54.835+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:14:54.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:14:54.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.058 seconds
[2025-04-23T20:15:25.719+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/test.py
[2025-04-23T20:15:25.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:15:25.729+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:15:25.727+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:15:25.828+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:15:25.796+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:15:25.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:15:25.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.196 seconds
[2025-04-23T20:15:56.773+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/test.py
[2025-04-23T20:15:56.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:15:56.778+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:15:56.777+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:15:56.803+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:15:56.796+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:15:56.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:15:56.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.067 seconds
[2025-04-23T20:16:27.570+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/test.py
[2025-04-23T20:16:27.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:16:27.574+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:16:27.574+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:16:27.596+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:16:27.591+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:16:27.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:16:27.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.073 seconds
[2025-04-23T20:16:58.386+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/test.py
[2025-04-23T20:16:58.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:16:58.391+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:16:58.391+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:16:58.418+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:16:58.410+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:16:58.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:16:58.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.065 seconds
[2025-04-23T20:17:29.294+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/test.py
[2025-04-23T20:17:29.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:17:29.305+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:17:29.305+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:17:29.345+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:17:29.336+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:17:29.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:17:29.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.112 seconds
[2025-04-23T20:20:31.641+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/test.py
[2025-04-23T20:20:31.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:20:31.647+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:20:31.647+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:20:31.678+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:20:31.670+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:20:31.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:20:31.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.073 seconds
[2025-04-23T20:21:02.320+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/test.py
[2025-04-23T20:21:02.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:21:02.326+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:21:02.326+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:21:02.353+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:21:02.347+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:21:02.356+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:21:02.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.075 seconds
[2025-04-23T20:21:33.015+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/test.py
[2025-04-23T20:21:33.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:21:33.019+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:21:33.018+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:21:33.041+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:21:33.036+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:21:33.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:21:33.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.056 seconds
[2025-04-23T20:22:03.698+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/test.py
[2025-04-23T20:22:03.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:22:03.703+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:22:03.703+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:22:03.736+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:22:03.729+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:22:03.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:22:03.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.078 seconds
[2025-04-23T20:22:34.457+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/test.py
[2025-04-23T20:22:34.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:22:34.463+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:22:34.462+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:22:34.486+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:22:34.480+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:22:34.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:22:34.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.062 seconds
[2025-04-23T20:23:04.801+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/test.py
[2025-04-23T20:23:04.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:23:04.805+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:23:04.805+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:23:04.827+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:23:04.822+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:23:04.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:23:06.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.058 seconds
[2025-04-23T20:23:38.879+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/test.py
[2025-04-23T20:23:38.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:23:38.883+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:23:38.883+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:23:38.905+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:23:38.901+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:23:38.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:23:38.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.064 seconds
[2025-04-23T20:24:09.183+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/test.py
[2025-04-23T20:24:09.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:24:09.187+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:24:09.187+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:24:09.209+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:24:09.203+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:24:09.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:24:09.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.055 seconds
[2025-04-23T20:24:40.001+0000] {processor.py:186} INFO - Started process (PID=287) to work on /opt/airflow/dags/test.py
[2025-04-23T20:24:40.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:24:40.005+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:24:40.005+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:24:40.027+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:24:40.022+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:24:40.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:24:40.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.058 seconds
[2025-04-23T20:25:10.816+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/test.py
[2025-04-23T20:25:10.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:25:10.823+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:25:10.822+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:25:10.862+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:25:10.853+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:25:10.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:25:10.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.086 seconds
[2025-04-23T20:25:41.621+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/test.py
[2025-04-23T20:25:41.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:25:41.625+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:25:41.624+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:25:41.645+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:25:41.640+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:25:41.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:25:41.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.050 seconds
[2025-04-23T20:26:12.225+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/test.py
[2025-04-23T20:26:12.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:26:12.229+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:26:12.228+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:26:12.254+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:26:12.249+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:26:12.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:26:12.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.055 seconds
[2025-04-23T20:26:42.898+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/test.py
[2025-04-23T20:26:42.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:26:42.901+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:26:42.901+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:26:42.921+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:26:42.916+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:26:42.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:26:42.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.064 seconds
[2025-04-23T20:27:13.619+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/test.py
[2025-04-23T20:27:13.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:27:13.626+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:27:13.625+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:27:13.659+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:27:13.652+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:27:13.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:27:13.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.092 seconds
[2025-04-23T20:27:43.832+0000] {processor.py:186} INFO - Started process (PID=377) to work on /opt/airflow/dags/test.py
[2025-04-23T20:27:43.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:27:43.836+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:27:43.835+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:27:43.857+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:27:43.852+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:27:43.859+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:27:43.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.055 seconds
[2025-04-23T20:28:14.847+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/airflow/dags/test.py
[2025-04-23T20:28:14.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:28:14.854+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:28:14.853+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:28:14.931+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:28:14.915+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:28:14.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:28:15.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.192 seconds
[2025-04-23T20:28:45.756+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/test.py
[2025-04-23T20:28:45.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:28:45.759+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:28:45.759+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:28:45.778+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:28:45.773+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:28:45.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:28:45.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.047 seconds
[2025-04-23T20:29:16.413+0000] {processor.py:186} INFO - Started process (PID=422) to work on /opt/airflow/dags/test.py
[2025-04-23T20:29:16.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:29:16.418+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:29:16.417+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:29:16.434+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:29:16.431+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:29:16.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:29:16.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2025-04-23T20:29:47.272+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/test.py
[2025-04-23T20:29:47.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:29:47.277+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:29:47.276+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:29:47.302+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:29:47.297+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:29:47.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:29:47.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.063 seconds
[2025-04-23T20:30:17.920+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/test.py
[2025-04-23T20:30:17.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:30:17.924+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:30:17.924+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:30:17.943+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:30:17.939+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:30:17.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:30:17.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.050 seconds
[2025-04-23T20:30:48.596+0000] {processor.py:186} INFO - Started process (PID=467) to work on /opt/airflow/dags/test.py
[2025-04-23T20:30:48.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:30:48.601+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:30:48.600+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:30:48.622+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:30:48.617+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:30:48.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:30:48.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.053 seconds
[2025-04-23T20:31:19.541+0000] {processor.py:186} INFO - Started process (PID=482) to work on /opt/airflow/dags/test.py
[2025-04-23T20:31:19.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:31:19.547+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:31:19.546+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:31:19.574+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:31:19.568+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:31:19.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:31:19.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.087 seconds
[2025-04-23T20:31:50.349+0000] {processor.py:186} INFO - Started process (PID=497) to work on /opt/airflow/dags/test.py
[2025-04-23T20:31:50.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:31:50.354+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:31:50.354+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:31:50.397+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:31:50.380+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:31:50.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:31:50.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.095 seconds
[2025-04-23T20:32:21.153+0000] {processor.py:186} INFO - Started process (PID=512) to work on /opt/airflow/dags/test.py
[2025-04-23T20:32:21.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:32:21.161+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:32:21.159+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:32:21.190+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:32:21.183+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:32:21.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:32:21.224+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.079 seconds
[2025-04-23T20:32:51.917+0000] {processor.py:186} INFO - Started process (PID=527) to work on /opt/airflow/dags/test.py
[2025-04-23T20:32:51.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:32:51.925+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:32:51.925+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:32:51.987+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:32:51.962+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:32:51.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:32:52.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2025-04-23T20:33:22.977+0000] {processor.py:186} INFO - Started process (PID=542) to work on /opt/airflow/dags/test.py
[2025-04-23T20:33:22.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:33:22.993+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:33:22.992+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:33:23.071+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:33:23.055+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:33:23.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:33:23.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.214 seconds
[2025-04-23T20:33:53.878+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/test.py
[2025-04-23T20:33:53.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:33:53.882+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:33:53.881+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:33:53.899+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:33:53.894+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:33:53.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:33:53.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2025-04-23T20:34:24.567+0000] {processor.py:186} INFO - Started process (PID=572) to work on /opt/airflow/dags/test.py
[2025-04-23T20:34:24.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:34:24.571+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:34:24.571+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:34:24.594+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:34:24.589+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:34:24.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:34:24.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.059 seconds
[2025-04-23T20:34:55.237+0000] {processor.py:186} INFO - Started process (PID=585) to work on /opt/airflow/dags/test.py
[2025-04-23T20:34:55.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:34:55.242+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:34:55.241+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:34:55.265+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:34:55.260+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:34:55.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:34:55.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.058 seconds
[2025-04-23T20:35:27.866+0000] {processor.py:186} INFO - Started process (PID=600) to work on /opt/airflow/dags/test.py
[2025-04-23T20:35:27.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:35:27.871+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:35:27.870+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:35:27.898+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:35:27.890+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:35:27.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:35:27.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.068 seconds
[2025-04-23T20:35:58.200+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/test.py
[2025-04-23T20:35:58.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-04-23T20:35:58.204+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:35:58.204+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-04-23T20:35:58.233+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:35:58.227+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:35:58.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-04-23T20:35:58.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.068 seconds
