[2025-03-03T07:07:44.000+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T07:07:44.026+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lab1_dag.extract scheduled__2025-03-03T07:00:00+00:00 [queued]>
[2025-03-03T07:07:44.034+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lab1_dag.extract scheduled__2025-03-03T07:00:00+00:00 [queued]>
[2025-03-03T07:07:44.036+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-03T07:07:44.048+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-03-03 07:00:00+00:00
[2025-03-03T07:07:44.076+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=293) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-03T07:07:44.080+0000] {standard_task_runner.py:72} INFO - Started process 296 to run task
[2025-03-03T07:07:44.069+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'lab1_dag', 'extract', 'scheduled__2025-03-03T07:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/lab1.py', '--cfg-path', '/tmp/tmpum278wkw']
[2025-03-03T07:07:44.082+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask extract
[2025-03-03T07:07:44.293+0000] {task_command.py:467} INFO - Running <TaskInstance: lab1_dag.extract scheduled__2025-03-03T07:00:00+00:00 [running]> on host 57f235e0432a
[2025-03-03T07:07:44.736+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lab1_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T07:00:00+00:00'
[2025-03-03T07:07:44.743+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-03T07:07:44.755+0000] {logging_mixin.py:190} INFO - YF.download() has changed argument auto_adjust default to True
[2025-03-03T07:07:44.764+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2025-03-03T07:07:45.727+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2025-03-03T07:07:45.729+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  2 of 2 completed
[2025-03-03T07:07:45.954+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T07:07:46.056+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-03T07:07:46.058+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=lab1_dag, task_id=extract, run_id=scheduled__2025-03-03T07:00:00+00:00, execution_date=20250303T070000, start_date=20250303T070744, end_date=20250303T070746
[2025-03-03T07:07:46.146+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T07:07:46.171+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-03T07:07:46.172+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
